# Generated by Django 6.0 on 2026-01-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': 'Developer', 'verbose_name_plural': 'Developers'},
        ),
        migrations.AlterModelOptions(
            name='hr',
            options={'verbose_name': 'HR', 'verbose_name_plural': 'HRs'},
        ),
    ]
